language: julia
os:
    - osx
    - linux
julia:
    - release
    - nightly
notifications:
    email: false
install: 
	"pip install sgp4"
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("SGP4"); Pkg.test("SGP4"; coverage=true)';
after_success:
    - julia -e 'cd(Pkg.dir("SGP4")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';